version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
  nodejs:
    build: .
    container_name: nodejs
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGO_URL: ${MONGO_URL}
      PORT: ${PORT}
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
